### ISSUE TITLE
error while installing decky loader

### ISSUE THREAD

**Issue by rayan629** [ACCESS-DENIIED/Decky-Loader-For-Windows#1]
hey, i love the project but i got a problem

Error: ERROR: file:///C:/Users/Rayan/Downloads/GamesDows-Decky.Installer.Full.Release/GamesDows-main/decky/Decky.Loader.Installer/app/backend does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
failed to install decky_loader package.

Greetings, Rayan

**Comment by julianrios** [comment]
Not sure if its related but I'm facing this error. Trying to install on my steam deck running windows 11 pro:
Error: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python  found, but version 3.11 is required

   - 
                                                                                                                        

   - 
                                                                                                                        
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
v18.18.0
Error: 'git' is not recognized as an internal or external command,
Error: operable program or batch file.

   - 
                                                                                                                        

   - 
                                                                                                                        
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.

changed 1 package in 3s

1 package is looking for funding
  run `npm fund` for details
Error: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Command failed with errors:
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Error: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Command failed with errors:
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Error: Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Failed to install required Python packages.

**Comment by ACCESS-DENIIED** [comment]
Thanks for the reports, guys! I'm aware of these issues but am currently taking a few days off to recharge.

If all goes well, we should have a fully automated executable to install decky loader, by the end of week.

**Comment by ACCESS-DENIIED** [comment]
I've just released a hotfix to address some of these issues. The application will likely error on the first attempt to install decky loader, but simply running the application again should now complete the process of installing decky loader and you'll also not likely see this error again following this. It's definitely something I intend to fully fix soon but the latest release should suffice until then. Please report back if you have any updates.

**Comment by julianrios** [comment]
thanks for the quick support. 

I ended up ditching steam deck windows dual boot setup if I go back to it I'll check this out!
